#!/bin/bash

exec >>/tmp/aerospace.log 2>&1

# shellcheck source=../dotinc/entrypoint.sh
. "${HOME}/.local/shell-include/entrypoint.sh"

MAX_LAUNCH_TRIES=5

TARGET="$1"
shift

if [ "$#" -eq 2 ] && [ "$1" == "--launch" ]; then
    WORKSPACE="$2"
fi

APPS="$(jq --arg win "$TARGET" '(.[$win] // {"apps": [$win]}).apps' ~/.config/aerospace/workspaces.json)"

_log "Focusing applications: $APPS"

_find_window() {
    WINDOW="$(aerospace list-windows --all --json | /usr/bin/tr -cd '[:print:]' | jq -r --argjson apps "$APPS" '.[] | select(.["app-name"] | IN($apps[])) | .["window-id"]' | sort | head -n 1)"
    if [ -n "${WINDOW}" ]; then
        _log "Found window ID: $WINDOW"
    else
        _log "No window found for applications: $APPS"
    fi
}

_find_window

if [ -z "${WINDOW}" ] && [ -n "$WORKSPACE" ]; then
    TO_LAUNCH="$(echo "$APPS" | jq -r '.[0]')"
    _log "Window not found, launching $TO_LAUNCH.app on $WORKSPACE"
    osascript -e "tell application \"$TO_LAUNCH\" to activate"
    TRIES=0

    while [ -z "${WINDOW}" ] && [ $TRIES -lt $MAX_LAUNCH_TRIES ]; do
        _log "Waiting for application to launch... (try $((TRIES + 1))/$MAX_LAUNCH_TRIES)"
        sleep 0.25
        _find_window
        TRIES=$((TRIES + 1))
    done

    aerospace move-node-to-workspace --window-id "$WINDOW" "$WORKSPACE"
elif [ -z "${WINDOW}" ]; then
    _log "No workspace specified, exiting"
    exit 0
fi

if [ -n "${WINDOW}" ]; then
    aerospace focus --window-id "$WINDOW"
fi
