#!/bin/bash

PROVIDER_KIND="$1"
PROVIDER_NAME="$2"
if [ -z "$PROVIDER_NAME" ]; then
    echo "Usage: $0 <provider_kind> <provider_name>" >&2
    exit 1
fi

CLIENT_ID="$(ak-client-id "${PROVIDER_KIND}" "${PROVIDER_NAME}")"

ak auth raw --client-id "${CLIENT_ID}"
