#!/bin/bash

exec >>/tmp/aerospace.log 2>&1

/usr/bin/find /Applications/ /Applications/Utilities/ /System/Applications/ /System/Applications/Utilities/ -mindepth 1 -maxdepth 1 -name '*.app' |
    /usr/bin/sed 's/\.app$//' |
    xargs -I{} /usr/bin/basename '{}' |
    choose -s 20 -n 16 -u -p 'App name...' -w 10 -c d79921 -b 111111 |
    /usr/bin/xargs -I {} open -a "{}.app"
