#!/bin/bash

brew install codex
auth

GITHUB_MCP_AUTH_TOKEN="$(ak-auth-provider proxy 'GitHub MCP')"
SPOTIFY_MCP_AUTH_TOKEN="$(ak-auth-provider proxy 'Spotify MCP')"

OPENPROJECT_MCP_TOKEN="$(vault-kv /openproject api_token)"
VIKUNJA_API_TOKEN="$(vault-kv /vikunja api_token)"

export \
    GITHUB_MCP_AUTH_TOKEN \
    SPOTIFY_MCP_AUTH_TOKEN \
    VIKUNJA_API_TOKEN \
    OPENPROJECT_MCP_TOKEN

/opt/homebrew/bin/codex "$@"
