#!/bin/bash

if [ -z "${ENCRYPT_PASSWORD}" ]; then
    read -rs -p "Enter Password: " ENCRYPT_PASSWORD
fi
export ENCRYPT_PASSWORD

openssl enc -aes-256-cbc -in "$1" -out "$1.enc" -md sha512 -pbkdf2 -iter 100000 -salt -pass env:ENCRYPT_PASSWORD
