#!/bin/bash

USERNAME="$(gh api user --jq .login)"
ON="${1:-$(date +%Y-%m-%d)}"

# github-my-repos
echo secuwelt-ai/secuwelt-workload | while read -r REPO; do
    echo "Checking ${REPO}" >/dev/stderr
    gh api "repos/${REPO}/actions/runs?actor=${USERNAME}&created=>=${ON}"
done | jq -r '.workflow_runs[] | [.created_at, .repository.full_name, .name, .head_branch, .status, .conclusion, .html_url] | @tsv' |
    column -t -s $'\t' |
    sort
