#!/bin/bash

# shellcheck source=../dotinc/entrypoint.sh
. "${HOME}/.local/shell-include/entrypoint.sh"

_usage() {
    _fatal "Usage: $0 <module>"
}

if [ "$#" -ne 1 ]; then
    _usage
fi

MODULE="$1"

SOURCE_ROOT="${HOME}/src/dre/dotfiles"
SOURCE="${SOURCE_ROOT}/${MODULE}"
NIX_ROOT="/nix/"
NIXCONFS=(
    "${HOME}/src/dre/dotfiles/nix/home/conf/common/files/dotconf.nix"
    "${HOME}/src/dre/dotfiles/nix/home/conf/home/files/dotconf.nix"
    "${HOME}/src/dre/dotfiles/nix/home/conf/work/files/dotconf.nix"
)

_rmlink() {
    local LINK="$1"
    local TARGET="$2"
    (
        if [ ! -e "${TARGET}" ]; then
            _warn "Skipping change check for '${TARGET}' - target does not exist"
            return
        fi
        if [ ! -d "${TARGET}" ]; then
            _info "Skipping change check for '${TARGET}' - target is not a directory"
            return
        fi
        cd "${TARGET}" 2>/dev/null || {
            _warn "Failed to change directory to '${TARGET}'"
            return
        }
        if [ ! -d ".git" ]; then
            _info "Skipping change check for '${TARGET}' - target is not a git repository"
            return
        fi
        if [ -n "$(git status --porcelain)" ]; then
            _warn "Directory '${TARGET}' has uncommitted changes!"
        fi
    )
    _info "Removing link for '${LINK}'"
    if [ "${DRY_RUN}" = "true" ]; then
        _info "Dry run enabled - skipping actual removal"
        return
    fi
    rm "${LINK}"
}

if [ "${MODULE}" = "clean" ]; then
    _info "Cleaning all linked modules"
    while IFS= read -r line; do
        # WARNING: No test -e -- returns 1 for broken symlinks!
        if [ ! -L "${HOME}/${line}" ]; then
            _warn "Skipping '${line}' - not a symlink"
            continue
        fi
        LINK="${HOME}/${line}"
        TARGET="$(realpath -m -- "${LINK}")"
        if [ -z "${TARGET}" ]; then
            _warn "Skipping '${line}' - failed to resolve link target"
            continue
        fi
        if [[ "${TARGET}" != "${NIX_ROOT}"* ]]; then
            _rmlink "${LINK}" "${TARGET}"
        else
            _info "Skipping '${line}' - link target '${TARGET}' is within Nix store"
            continue
        fi
    done < <(/usr/bin/grep -oE '"[a-zA-Z0-9./_-]+"\.source' "${NIXCONFS[@]}" | cut -d '"' -f 2)
    exit 0
fi

if [ ! -d "${SOURCE}" ]; then
    _fatal "Module '${MODULE}' does not exist at '${SOURCE}'"
fi

TARGET_DIR="${HOME}/$(/usr/bin/grep "${MODULE}" "${NIXCONFS[@]}" | /usr/bin/grep -oE '"[a-zA-Z0-9./_-]+"\.source' | cut -d '"' -f 2)"

LINK_TARGET=
if [ -L "${TARGET_DIR}" ]; then
    LINK_TARGET="$(readlink -f "${TARGET_DIR}")"
fi

if [[ "${LINK_TARGET}" == "${SOURCE}" ]]; then
    _rmlink "${TARGET_DIR}"
else
    _info "Linking module '${MODULE}' locally"
    ln -sfn "${SOURCE}" "${TARGET_DIR}"
fi
