#!/bin/bash

# shellcheck source=../dotinc/entrypoint.sh
. "${HOME}/.local/shell-include/entrypoint.sh"

_usage() {
    _fatal "Usage: $0 <module>"
}

if [ "$#" -ne 1 ]; then
    _usage
fi

MODULE="$1"

SOURCE_ROOT="${HOME}/src/dre/dotfiles"
SOURCE="${SOURCE_ROOT}/${MODULE}"
NIXCONF="${HOME}/src/dre/dotfiles/nix/home/conf/common/files/dotconf.nix"

_rmlink() {
    local TARGET="$1"
    (
        cd "${TARGET}" || _fatal "Failed to change directory to '${TARGET}'"
        if [ -n "$(git status --porcelain)" ]; then
            _warn "Directory '${TARGET}' has uncommitted changes!"
        fi
    )
    _info "Removing link for '${TARGET}'"
    rm "${TARGET}"
}

if [ "${MODULE}" = "clean" ]; then
    _info "Cleaning all linked modules"
    while IFS= read -r line; do
        if [ ! -e "${HOME}/${line}" ]; then
            _info "Skipping '${line}' - target does not exist"
            continue
        fi
        if [ ! -L "${HOME}/${line}" ]; then
            _warn "Skipping '${line}' - not a symlink"
            continue
        fi
        TARGET="$(readlink -f "${HOME}/${line}")"
        if [[ "${TARGET}" == "${SOURCE_ROOT}"* ]]; then
            _rmlink "${HOME}/${line}"
        else
            _info "Skipping '${line}' - link target '${TARGET}' is outside of source root"
            continue
        fi
    done < <(/usr/bin/grep -oE '"[a-zA-Z0-9./_-]+"\.source' "${NIXCONF}" | cut -d '"' -f 2)
    exit 0
fi

if [ ! -d "${SOURCE}" ]; then
    _fatal "Module '${MODULE}' does not exist at '${SOURCE}'"
fi

TARGET_DIR="${HOME}/$(/usr/bin/grep "${MODULE}" "${NIXCONF}" | /usr/bin/grep -oE '"[a-zA-Z0-9./_-]+"\.source' | cut -d '"' -f 2)"

LINK_TARGET=
if [ -L "${TARGET_DIR}" ]; then
    LINK_TARGET="$(readlink -f "${TARGET_DIR}")"
fi

if [[ "${LINK_TARGET}" == "${SOURCE}" ]]; then
    _rmlink "${TARGET_DIR}"
else
    _info "Linking module '${MODULE}' locally"
    ln -sfn "${SOURCE}" "${TARGET_DIR}"
fi
