#!/usr/bin/env bash

# shellcheck source=../dotinc/entrypoint.sh
source "${HOME}/.local/include/entrypoint.sh"

set -eEuo pipefail

if [ ! -d .git ]; then
    yesno "Do you want to initialize a new repository?" "git init"
fi

REPO="${GITHUB_ORG}/${1}"

if gh repo view "${REPO}" >/dev/null 2>&1; then
    yesno "Repository ${REPO} already exists - add remote?"
else
    gh repo create \
        --private \
        "${REPO}"
fi

REPO_DATA=$(gh repo view --json sshUrl,url "${REPO}")
REPO_URL=$(echo "${REPO_DATA}" | jq -r '.url')
REPO_SSH_URL=$(echo "${REPO_DATA}" | jq -r '.sshUrl')

_log "Repository HTTP URL at: ${REPO_URL}"

git remote add origin "${REPO_SSH_URL}"

_log "Remote added to local repository: ${REPO_SSH_URL}"
